### ISSUE TITLE
Exclude empty values when filter on relation returns empty

### ISSUE THREAD

**Issue by minottic** [SciCatProject/panosc-search-api#17]
## Issue Name
Exclude empty values when filter on relation returns empty
### Summary
When a query with a loopback formatted filter containing a where condition on a relation is applied, results with such empty filtered relation are returned. Desire to filter out such records.
### Steps to Reproduce
1. Open the explorer
2. Apply this filter in the dataset get method `{     "include": [         {             "relation": "files",             "scope": {                 "where": {                     "name": "meta_test_01.h5"                 }             }         }     ]}`
3. all dataset records are returned, the ones with a matching condition on the relation have a non empty files list, the others have an empty file list
### Current Behaviour
In point (3.) of `Steps to Reproduce` the records having the relation empty list are returned
### Expected Behaviour
In point (3.) of `Steps to Reproduce` the records having the relation empty list should not be returned
### Extra Details
![image](https://user-images.githubusercontent.com/50220438/114057258-b25cb780-9892-11eb-8924-9ef2a3f94932.png)

Here you should include details about the system (if it is unique) and possible information about a fix (feel free to link to code where relevant). Screenshots/GIFs are also fine here.

**Comment by minottic** [comment]
loopback syntax allows to query including more than one relation, e.g.: `{     "include": [         {             "relation": "files",             "scope": {                 "where": {                     "name": "meta_test_01.h5"                 }             }         }     , {             "relation": "techniques",             "scope": {                 "where": {                     "name": "meta_test_01.h5"                 }             }         } ]}`
Do we want the intended solution to filter out records after the filter is applied, which have an empty relation on the first **or** on the second relation or on the first **and** on the second?

**Comment by stephan271** [comment]
I would go for the **and** case
